'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { api, employees as fallbackEmployees } from '@/lib/api';
import { Avatar, CountUp, Reveal } from './DesignSystem';
import { usePathname } from 'next/navigation';

type Employee = { id: string; name: string; role: string; language: string; callsToday: number; status: string };
type Summary = { employeesWorking: number; conversationsHandled: number; qualifiedLeads: number; creditsSpent: number };
const nav = [['Overview','/dashboard'],['Employees','/dashboard/employees'],['Calls','/dashboard/calls'],['Leads','/dashboard/leads'],['Billing','/dashboard/billing'],['Integrations','/dashboard/integrations']];

export function Dashboard({ page = 'Overview' }: { page?: string }) { const path = usePathname(); return <div className="min-h-screen bg-[#fafaff]"><header className="border-b border-line bg-white"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-4"><Link href="/" className="flex items-center gap-2 text-[13px] font-extrabold tracking-[-.06em]"><span className="grid h-5 w-5 place-items-center rounded-md bg-primary text-[10px] text-white">S</span>svara<span className="-ml-2 text-primary">labs</span></Link><CreditBalance /></div></header><main className="mx-auto max-w-[1180px] px-5 py-7"><nav className="flex max-w-full gap-1 overflow-x-auto rounded-xl border border-line bg-white p-1" aria-label="Dashboard navigation">{nav.map(([label, href]) => <Link key={label} className={`whitespace-nowrap rounded-lg px-3 py-2 text-[10px] font-bold ${path === href ? 'bg-primary text-white' : 'text-ink/55'}`} href={href}>{label}</Link>)}</nav><div className="mt-8"><span className="eyebrow-ref">Svara workspace</span><h1 className="mt-2 text-[30px] font-extrabold tracking-[-.055em]">{page}</h1></div>{page === 'Overview' ? <Overview /> : page === 'Employees' ? <Employees /> : <DataPage page={page} />}</main></div> }

function CreditBalance() { const [balance,setBalance] = useState(8460); useEffect(()=>{api<{balance:number}>('/api/credits/balance',undefined,{balance:8460}).then(x=>setBalance(x.balance));},[]); return <div className="rounded-full bg-[#f0f1ff] px-3 py-2 text-[10px] font-bold text-primary">Credits: ₹{balance.toLocaleString('en-IN')}</div> }
function Overview() { const [summary,setSummary] = useState<Summary>({employeesWorking:3,conversationsHandled:127,qualifiedLeads:41,creditsSpent:2840}); const [team,setTeam] = useState<Employee[]>(fallbackEmployees); useEffect(()=>{api<Summary>('/api/dashboard/summary',undefined,summary).then(setSummary);api<Employee[]>('/api/employees',undefined,fallbackEmployees).then(setTeam)},[]); const stats = [[summary.employeesWorking,'Employees working',''],[summary.conversationsHandled,'Conversations handled',''],[summary.qualifiedLeads,'Qualified leads',''],[summary.creditsSpent,'Credits spent','₹']]; return <><Reveal className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{stats.map(([value,label,prefix])=><div className="card-interactive p-5" key={String(label)}><b className="text-3xl"><CountUp value={Number(value)} prefix={String(prefix)} /></b><p className="mt-2 text-[11px] text-ink/55">{String(label)} <span className="text-success">↑ 18%</span></p></div>)}</Reveal><div className="mt-6 grid gap-5 lg:grid-cols-[1.45fr_.8fr]"><section className="card p-5"><div className="flex justify-between"><h2 className="font-extrabold">Your AI employees</h2><Link href="/dashboard/employees" className="text-[10px] font-bold text-primary">View team →</Link></div><div className="mt-5 space-y-2">{team.map(e=><Link href={`/dashboard/employees/${e.id}`} className="grid grid-cols-[auto_1fr_auto] items-center gap-3 rounded-xl bg-[#f8f8ff] p-3 transition hover:bg-[#eff0ff]" key={e.id}><Avatar name={e.name as 'Anaya'|'Tara'|'Rohan'} size="sm"/><span><b className="text-[11px]">{e.name}</b><small className="mt-1 block text-[9px] text-ink/50">{e.role} · {e.language}</small></span><span className="text-[9px] font-bold text-success">● {e.status}</span></Link>)}</div></section><aside className="grain rounded-[16px] bg-ink p-5 text-white"><span className="text-[9px] font-bold uppercase tracking-[.12em] text-white/45">Attention needed</span><div className="relative mt-4 space-y-3 text-[10px]"><p className="rounded-lg bg-white/10 p-3"><b>2 calls</b> need a manual follow-up.</p><p className="rounded-lg bg-white/10 p-3"><b>₹8,460</b> remains in your credit wallet.</p><p className="rounded-lg bg-white/10 p-3">Anaya’s script changed at 10:32 AM.</p></div></aside></div></> }
function Employees() { const [team,setTeam]=useState<Employee[]>(fallbackEmployees);useEffect(()=>{api<Employee[]>('/api/employees',undefined,fallbackEmployees).then(setTeam)},[]);return <Reveal className="mt-7 grid gap-4 md:grid-cols-3">{team.map(e=><Link href={`/dashboard/employees/${e.id}`} key={e.id} className="card-interactive p-6"><Avatar name={e.name as 'Anaya'|'Tara'|'Rohan'}/><h2 className="mt-6 font-extrabold">{e.name}</h2><p className="mt-1 text-[10px] text-ink/55">{e.role} · {e.language}</p><div className="mt-5 flex justify-between border-t border-line pt-4 text-[10px]"><span className="font-bold text-success">● {e.status}</span><b>{e.callsToday} calls</b></div></Link>)}</Reveal> }
function DataPage({page}:{page:string}) { const [rows,setRows]=useState<string[]>([]); useEffect(()=>{const info:Record<string,[string,unknown,string[]]>={Calls:['/api/calls',[],['Priya Sharma · Completed · 12m 48s','Vikram Singh · Completed · 6m 22s']],Leads:['/api/leads',[],['Priya Sharma · Meta form · Qualified','Vikram Singh · Website · Meeting booked']],Billing:['/api/pricing/plans',[],['Available balance · ₹8,460','Growth talk-time · ₹4.50/min']],Integrations:['/api/integrations',[],['HubSpot · Connected · 4 mins ago','Google Sheets · Connected · 8 mins ago','WhatsApp · Ready to connect']], 'Employee profile':['/api/employees/anaya',{},['Anaya · Sales specialist','Recent calls available in call history']]};const [endpoint,fallback,defaults]=info[page]??info.Calls;api<unknown>(endpoint,undefined,fallback).then(data=>{if(Array.isArray(data))setRows(data.map((row:any)=>row.leadName?`${row.leadName} · ${row.status} · ${row.duration}`:row.name?`${row.name} · ₹${row.pricePerMin}/min`:row.type?`${row.type} · ${row.connected?'Connected':'Ready to connect'}`:String(row)));else setRows(defaults)});},[page]);return <section className="card mt-7 p-5"><p className="text-[11px] text-ink/55">Live workspace data with resilient local fallback while an external API is unavailable.</p><div className="mt-5 space-y-2">{(rows.length?rows:['Loading workspace data…']).map(row=><div className="rounded-xl bg-[#f8f8ff] p-4 text-[11px] font-semibold" key={row}>{row}</div>)}</div></section> }
