'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useRef, useState } from 'react';
import { api } from '@/lib/api';
import { IncomingCall } from '@/components/ui/incoming-call';
import { Footer } from './Footer';

const cx = (...values: Array<string | false | undefined>) => values.filter(Boolean).join(' ');
const Icon = ({ children, tone = 'blue' }: { children: React.ReactNode; tone?: 'blue' | 'mint' | 'gold' | 'pink' }) => <span className={`icon ${tone}`}>{children}</span>;
const Dots = () => <div aria-hidden className="reference-dots" />;
type DemoResponse = { callId: string; status: string; estimatedWaitSeconds?: number };
type Plan = { id: string; name: string; pricePerMin: number; features: string[]; description?: string; badge?: string };

function BrandHeader() {
  const [open, setOpen] = useState(false);
  const links = [['How it works', '#how'], ['Why Svara', '#why'], ['Capabilities', '#features'], ['Pricing', '#pricing'], ['Compare', '#compare'], ['FAQ', '#faq'], ['Docs', '/dashboard']];
  return <header className="relative z-30 mx-auto flex h-16 max-w-[1180px] items-center justify-between px-5">
    <Link href="/" className="flex items-center gap-2 text-[14px] font-extrabold tracking-[-.06em]"><span className="grid h-6 w-6 place-items-center rounded-md bg-primary text-[10px] text-white">S</span><span>svara<span className="text-primary">labs</span></span></Link>
    <nav className="hidden items-center gap-5 text-[11px] font-semibold text-ink/60 lg:flex">{links.map(([label, href]) => href.startsWith('/') ? <Link key={label} href={href}>{label}</Link> : <a key={label} href={href}>{label}</a>)}</nav>
    <div className="hidden items-center gap-4 md:flex"><Link href="/login" className="text-[11px] font-bold text-ink/70">Log in</Link><Link href="/signup" className="action action-primary !px-4 !py-2">Start free</Link></div>
    <button aria-expanded={open} aria-label="Open navigation" onClick={() => setOpen(!open)} className="grid h-9 w-9 place-items-center rounded-lg text-primary md:hidden">☰</button>
    {open && <div className="absolute left-4 right-4 top-14 rounded-2xl border border-line bg-white p-4 shadow-soft md:hidden">{links.map(([label, href]) => href.startsWith('/') ? <Link className="mobile-link" key={label} onClick={() => setOpen(false)} href={href}>{label}</Link> : <a className="mobile-link" key={label} onClick={() => setOpen(false)} href={href}>{label}</a>)}<Link className="action action-primary mt-3 w-full" href="/signup">Start free</Link></div>}
  </header>;
}

function DemoRequestForm({ compact = false, showBrief = false, onQueued }: { compact?: boolean; showBrief?: boolean; onQueued?: (response: DemoResponse, phone: string, language: string) => void }) {
  const [phone, setPhone] = useState('');
  const [language, setLanguage] = useState('Hindi');
  const [brief, setBrief] = useState('');
  const [fileName, setFileName] = useState('');
  const [state, setState] = useState<'idle' | 'loading' | 'sent' | 'invalid'>('idle');
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (phone.replace(/\D/g, '').length < 8) return setState('invalid');
    setState('loading');
    const response = await api<DemoResponse>('/api/demo/call', { method: 'POST', body: JSON.stringify({ phone, language, businessDescription: brief || 'Svara website demo', source: showBrief ? 'hero' : 'call-simulator', attachmentName: fileName || undefined }) }, { callId: `local-${Date.now()}`, status: 'queued', estimatedWaitSeconds: 24 });
    setState('sent');
    onQueued?.(response, phone, language);
  };
  return <form onSubmit={submit} className={cx('lead-card', compact && 'lead-card-compact', showBrief && 'lead-card-brief')}>
    {showBrief && <><label className="script-field"><span>What should your employee handle?</span><textarea value={brief} onChange={(event) => setBrief(event.target.value)} placeholder="Describe your business, the kind of calls, and what a qualified outcome looks like." rows={3} /></label><label className="file-pill"><input type="file" accept=".pdf,.doc,.docx,.txt" onChange={(event) => setFileName(event.target.files?.[0]?.name || '')} /><span>＋ Attach call notes</span><small>{fileName || 'Optional'}</small></label></>}
    <div className="flex min-w-0 flex-1 items-center gap-3"><Icon>☎</Icon><div className="min-w-0 flex-1"><label className="block text-[9px] font-bold uppercase tracking-[.12em] text-ink/45">Where should Svara call?</label><input aria-label="Phone number" type="tel" value={phone} onChange={(event) => { setPhone(event.target.value); setState('idle'); }} placeholder="Enter your phone number" className="mt-1 w-full bg-transparent text-xs font-semibold outline-none placeholder:text-ink/30" /></div></div>
    <div className="language-choice" aria-label="Preferred call language">{['Hindi', 'English', 'Telugu'].map((item) => <button key={item} type="button" className={language === item ? 'active' : ''} onClick={() => setLanguage(item)}>{item}</button>)}</div>
    <button className="action action-primary shrink-0 !px-4 !py-2.5" disabled={state === 'loading'} type="submit">{state === 'loading' ? 'Queuing…' : state === 'sent' ? 'Call queued ✓' : 'Get a call'}</button>
    {state === 'invalid' && <p role="alert" className="basis-full text-[10px] font-medium text-red-600">Add a valid phone number to receive the sample call.</p>}
    {state === 'sent' && !compact && <p role="status" className="basis-full text-[10px] font-medium text-success">Request received. Your sample-call flow is now queued.</p>}
  </form>;
}

function Hero() {
  return <section id="top" className="hero-shell"><Dots /><BrandHeader /><div className="relative mx-auto max-w-[680px] px-5 pb-14 pt-14 text-center md:pb-20 md:pt-20"><span className="eyebrow-ref">AI calling teams for Indian businesses</span><h1 className="mt-4 text-[38px] font-extrabold leading-[.97] tracking-[-.065em] text-ink md:text-[60px]">Every good lead gets<br /><span className="text-primary">a thoughtful first call.</span></h1><p className="mx-auto mt-4 max-w-[490px] text-[13px] leading-5 text-ink/60">Give Svara a script or a goal. Your AI employee qualifies, follows up, and sends useful context to the tools your team already trusts.</p><div className="mt-7"><DemoRequestForm showBrief /></div><div className="mt-4 flex flex-wrap justify-center gap-x-5 gap-y-2 text-[9px] font-semibold text-ink/45"><span>✦ No card required for a demo</span><span>✦ Your script stays editable</span><span>✦ Live talk-time is transparent</span></div></div></section>;
}

function ProofBar() { const items = ['Calls qualified leads promptly', 'Hindi, English & Telugu', 'CRM-ready summaries', 'WhatsApp actions mid-call', 'Clear usage reporting', 'Human review controls']; return <div className="border-y border-line bg-white"><div className="proof-track mx-auto flex max-w-[1180px] flex-wrap justify-center gap-x-8 gap-y-3 px-5 py-4 text-[10px] font-semibold text-ink/50">{items.map((item) => <span key={item}>◌ {item}</span>)}</div></div>; }

function SetupVisual() { return <div className="relative mx-auto mt-9 min-h-[245px] max-w-[640px]"><div className="mock-window absolute left-0 top-5 w-[48%] p-4"><div className="flex items-center justify-between"><span className="text-[9px] font-bold">Anaya’s call plan</span><span className="status-chip">Ready</span></div><div className="mt-5 space-y-3"><div className="skeleton h-10" /><div className="skeleton h-10 w-[83%]" /><div className="flex gap-2"><span className="tag">Hindi</span><span className="tag">Warm voice</span></div></div><div className="mt-5 rounded-lg bg-lilac p-2 text-[9px] font-bold text-primary">Save & start calling</div></div><div className="absolute right-0 top-0 w-[57%] space-y-2"><div className="float-card rotate-[1deg]"><Icon tone="gold">●</Icon><div><b>Brochure sent on WhatsApp</b><p>Priya received “Premium plan.pdf”</p></div></div><div className="float-card -rotate-[1deg]"><Icon tone="blue">✓</Icon><div><b>Meeting booked, instantly</b><p>Tuesday · 3:30 PM · Sales calendar</p></div></div><div className="float-card ml-5 rotate-[1deg]"><Icon tone="mint">↗</Icon><div><b>Every answer logged</b><p>Budget, timeline and sentiment saved</p></div></div></div></div>; }
function LaunchPanel() { return <section id="how" className="section-ref section-tight"><div className="mx-auto max-w-[580px] text-center"><span className="eyebrow-ref">No agency middleman</span><h2 className="heading-ref mt-3">Shape the first call yourself.<br /><span className="text-primary">Launch the workflow when it feels right.</span></h2><p className="body-ref mt-3">Choose a language, map a few questions, and see a lead move from form fill to a qualified next action.</p></div><SetupVisual /></section>; }
function HowSteps() { const steps = [['01', 'Brief your employee', 'Set the voice, language, boundaries and qualification questions in a short setup.'], ['02', 'It calls live', 'Svara responds to an eligible lead and can send approved actions during the conversation.'], ['03', 'Every detail is logged', 'A summary, sentiment, captured fields and next step land in your workspace.']]; return <section className="mx-auto max-w-[1180px] px-5 pb-14"><div className="step-story">{steps.map(([number, title, copy]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>; }

function WorkModes() {
  const [mode, setMode] = useState<'instant' | 'bulk'>('instant');
  const steps = mode === 'instant' ? [['New lead arrives', 'Website form · Aarti Rao'], ['Svara calls in 24 sec', 'Hindi · sales qualification'], ['Booked & logged', 'Tue 3:30 PM · HubSpot']] : [['List is uploaded', '428 contacts · September campaign'], ['Svara works through it', '3 live conversations now'], ['Every result lands', '86 qualified · 12 follow-ups']];
  return <section className="section-ref pt-8"><div className="mx-auto max-w-[860px]"><div className="flex flex-col items-start justify-between gap-5 sm:flex-row sm:items-end"><div><span className="eyebrow-ref">One employee, two ways to work</span><h2 className="heading-ref mt-2">Never leave a warm lead<br />waiting for your team.</h2></div><div className="segmented" role="tablist" aria-label="Calling mode"><button role="tab" aria-selected={mode === 'instant'} onClick={() => setMode('instant')} className={cx(mode === 'instant' && 'selected')}>Instant leads</button><button role="tab" aria-selected={mode === 'bulk'} onClick={() => setMode('bulk')} className={cx(mode === 'bulk' && 'selected')}>Bulk campaigns</button></div></div><div className="workflow-screen mt-7"><div className="workflow-nav"><span className="brand-mini">S</span><span>Live queue</span><span>Employees</span><span>Calls</span><span>Insights</span></div><div className="min-w-0 flex-1 p-4 sm:p-6"><div className="flex items-center justify-between"><div><b className="text-sm">{mode === 'bulk' ? 'September reactivation' : 'New lead workflow'}</b><p className="mt-1 text-[10px] text-ink/45">Svara is handling the next best action.</p></div><span className="status-chip">● Live</span></div><div className="mt-6 grid gap-3 md:grid-cols-3">{steps.map(([title, detail], index) => <div className="workflow-step" key={title}><span className="step-no">0{index + 1}</span><div className="mt-6 h-9 w-9 rounded-xl bg-lilac" /><b className="mt-5 block text-[11px]">{title}</b><p>{detail}</p>{index < 2 && <i className="connector">→</i>}</div>)}</div></div></div><p className="workflow-footnote">Inbound calling is being designed separately, so it is not represented as a live feature.</p></div></section>;
}

const capabilityData = [
  ['Natural conversations', 'A calling voice tuned for Hindi-English switching, not a robotic IVR.', 'wave'], ['Working number setup', 'Prepare a number and script before your first campaign.', 'number'], ['Instant CRM sync', 'Map captured answers to HubSpot, Zoho or Sheets.', 'crm'], ['Consent-aware controls', 'Script guardrails, opt-out capture and recording controls.', 'shield'], ['Retries that know when to stop', 'Schedule the next attempt instead of looping callers.', 'retry'], ['Every lead source, one queue', 'Meta, website, CSV and webhook leads arrive together.', 'source'],
];
function TinyArt({ type }: { type: string }) { if (type === 'wave') return <div className="tiny-wave">{[10, 18, 27, 14, 35, 22, 11, 26, 15].map((height, index) => <i key={index} style={{ height }} />)}</div>; if (type === 'crm') return <div className="tiny-rows"><i /><i /><i /></div>; if (type === 'shield') return <div className="shield-art">✓</div>; if (type === 'retry') return <div className="retry-art">↻<span>+2h</span></div>; if (type === 'source') return <div className="source-art"><i /><i /><i /></div>; return <div className="number-art">+91 <b>80 4123 0928</b><span>Ready</span></div>; }
function Capabilities() { return <section id="features" className="section-ref pt-8"><div className="mx-auto max-w-[1180px]"><div className="mb-6"><span className="eyebrow-ref">Built for a real call floor</span><h2 className="heading-ref mt-2">The details that make<br />an AI employee useful.</h2></div><div className="capability-rail">{capabilityData.map(([title, text, art], index) => <article className={cx('capability-card', index === 0 && 'featured')} key={title}><TinyArt type={art} /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>; }

const roles = [
  ['Real estate', 'Lead qualification', 'M'], ['Coaching', 'Course admissions', 'C'], ['Hospitals', 'Patient follow-ups', 'H'], ['Restaurants', 'Reservation calls', 'R'], ['Insurance', 'Policy reminders', 'I'], ['Auto showrooms', 'Test-drive scheduling', 'A'], ['E-commerce', 'Order confirmation', 'E'], ['Recruiting', 'Initial screening', 'T'],
];
function IndustryBand() {
  const rail = useRef<HTMLDivElement>(null);
  const [selected, setSelected] = useState('');
  const scroll = (direction: number) => rail.current?.scrollBy({ left: direction * 260, behavior: 'smooth' });
  return <section id="why" className="industry-band"><div className="mx-auto max-w-[1180px] px-5 py-14"><div className="flex items-end justify-between gap-4"><div><span className="eyebrow-ref !text-[#c3e3c7]">Industry workflows</span><h2 className="mt-2 text-[28px] font-extrabold leading-none tracking-[-.05em] text-white md:text-[36px]">A caller for work that<br />still needs a human touch.</h2><p className="mt-3 max-w-sm text-[12px] leading-5 text-white/70">Start with a tested playbook, then adjust the question, handoff and outcome for your team.</p></div><div className="hidden gap-2 sm:flex"><button type="button" aria-label="Previous industries" onClick={() => scroll(-1)} className="carousel-button">←</button><button type="button" aria-label="Next industries" onClick={() => scroll(1)} className="carousel-button">→</button></div></div><div ref={rail} className="industry-rail mt-8">{roles.map(([industry, task, initial], index) => <article className="role-card" key={industry}><span className={`role-stripe stripe-${index % 5}`} /><span className="role-avatar">{initial}</span><p className="role-label">{task}</p><h3>{industry}</h3><p className="role-copy">Calls, follows up, and keeps the next step moving with a workflow you can review.</p><button type="button" onClick={() => setSelected(`${industry} playbook selected. Configure it in your workspace.`)}>View playbook →</button></article>)}</div><p className="industry-feedback" aria-live="polite">{selected}</p></div></section>;
}

function CallSimulator() {
  const [stage, setStage] = useState<'ready' | 'ringing' | 'talking' | 'complete'>('ready');
  const [call, setCall] = useState<DemoResponse | null>(null);
  const [detail, setDetail] = useState('Enter your number to preview the sample call flow.');
  const queued = (response: DemoResponse, phone: string, language: string) => { setCall(response); setDetail(`Demo queued for ${phone}. The ${language} call preview is ready.`); window.setTimeout(() => setStage('ringing'), 550); };
  const respond = async (answer: 'accepted' | 'declined') => { if (call) await api(`/api/demo/call/${call.callId}/${answer}`, { method: 'POST', body: JSON.stringify({ callId: call.callId }) }, { status: answer }); setStage(answer === 'accepted' ? 'talking' : 'ready'); setDetail(answer === 'accepted' ? 'Preview connected. The conversation and next action are being captured.' : 'Preview dismissed. You can queue another demo whenever you are ready.'); };
  return <div className="call-simulator"><div><DemoRequestForm compact onQueued={queued} /><p className="mt-3 text-[10px] text-ink/50" aria-live="polite">{detail}</p></div><div className="caller-card mx-auto"><span className="caller-status">{stage === 'ready' ? 'READY TO CALL' : stage === 'ringing' ? 'INCOMING CALL' : stage === 'talking' ? 'LIVE PREVIEW' : 'COMPLETE'}</span><div className="caller-avatar">S</div><h3>Svara assistant</h3><p>AI calling employee · your selected language</p>{stage === 'talking' && <><p className="mt-4 rounded-xl bg-lilac p-3 text-[10px] leading-4 text-ink/65">“Hello, thanks for trying Svara. What outcome should we capture after a good lead conversation?”</p><div className="talk-wave">{[11, 18, 28, 14, 35, 25, 17, 30, 12].map((height, index) => <i key={index} style={{ height }} />)}</div><button className="caller-button" onClick={() => { setStage('complete'); setDetail('Preview completed. A sample summary is ready in the workspace.'); }}>Finish preview</button></>}</div><IncomingCall isOpen={stage === 'ringing'} callerName="Svara assistant" callerInfo="demo" statusText="is ready to preview your call flow" onAccept={() => respond('accepted')} onDecline={() => respond('declined')} onClose={() => respond('declined')} /></div>;
}

function EmployeeStory() { return <section className="story-wash"><div className="section-ref py-16 md:py-24"><div className="grid items-center gap-10 md:grid-cols-[1fr_.78fr]"><div><span className="eyebrow-ref">Try the call flow</span><h2 className="heading-ref mt-3">See the AI employee<br /><span className="text-primary">call your number.</span></h2><p className="body-ref mt-4 max-w-md">This is a frontend preview of the API-backed demo request. Accept it to see how a call can pass into a summary and next action.</p></div><CallSimulator /></div><div className="story-grid mt-24"><div className="story-copy"><span className="eyebrow-ref">Continuity, without repetition</span><h3>Context carries forward.</h3><p>When Priya calls back, Svara can surface the last question, preferred location and next action for review.</p></div><div className="chat-art"><div className="chat-their">Hi, is the Koramangala home still available?</div><div className="chat-our">I can see the last viewing request. Would Tuesday afternoon work for a follow-up?</div><span>Conversation context synced</span></div><div className="summary-art"><span className="eyebrow-ref">Call summary</span><h3>Useful notes, every time.</h3><div className="summary-line"><span>Duration</span><b>08m 24s</b></div><div className="summary-line"><span>Budget</span><b>₹45L to ₹60L</b></div><div className="summary-line"><span>Sentiment</span><b className="text-success">Highly positive</b></div></div><div className="story-copy"><span className="eyebrow-ref">Use the moment</span><h3>Live in-call actions.</h3><p>Send a brochure, add a calendar hold, or tag a follow-up while the caller is still engaged.</p></div><div className="action-art"><div><Icon tone="mint">✓</Icon><span><b>WhatsApp sent</b><small>Floor plan delivered to Priya</small></span></div><div><Icon tone="gold">□</Icon><span><b>Viewing booked</b><small>Tuesday · 3:30 PM</small></span></div></div><div className="story-copy"><span className="eyebrow-ref">Resilience controls</span><h3>Clear recovery states.</h3><p>Surface a retry or carrier issue to your team instead of leaving a lead in an unknown state.</p></div><div className="terminal-art"><span>08:42:10 carrier signal below threshold</span><span>08:42:11 retry route prepared…</span><span className="good">08:42:12 alternate route established</span><span className="good">08:42:12 conversation state saved ✓</span></div></div></div></section>; }

function DataAndDashboard() { return <section className="section-ref pb-12"><div className="text-center"><span className="eyebrow-ref">No copy-paste required</span><h2 className="heading-ref mt-2">Data in. Data out. Clearly connected.</h2></div><div className="data-flow mt-8"><div><span className="data-icon">IN</span><b>Lead source</b><p>Form, CSV or webhook</p></div><i>→</i><div><span className="data-icon">AI</span><b>Call workflow</b><p>Script, outcome, action</p></div><i>→</i><div><span className="data-icon">OUT</span><b>Your workspace</b><p>CRM, Sheets, WhatsApp</p></div></div><div className="mt-16 text-center"><span className="eyebrow-ref">A calm dashboard</span><h2 className="heading-ref mt-2">The team view, without the noise.</h2></div><div className="dashboard-art mx-auto mt-8 max-w-[800px]"><Dots /><div className="dash-top"><div><span>Today’s calling team</span><h3>Good afternoon. Here is what needs a decision.</h3></div><span>3 active</span></div><div className="dash-stats"><div><b>127</b><span>Conversations</span></div><div><b>41</b><span>Qualified</span></div><div><b>18</b><span>Follow-ups</span></div><div><b>₹2.8k</b><span>Credits used</span></div></div><div className="dash-list"><div><span className="dash-avatar">A</span><b>Anaya<small>Sales specialist</small></b><span>36 calls</span><span className="dash-live">● Calling</span></div><div><span className="dash-avatar">T</span><b>Tara<small>Support guide</small></b><span>24 calls</span><span className="dash-live">● Available</span></div><div><span className="dash-avatar">R</span><b>Rohan<small>Follow-up expert</small></b><span>19 calls</span><button>Review</button></div></div></div></section>; }

function CompareTable() { const rows = [['Cost model', 'Usage-based talk time', 'Monthly salary', 'Platform fee + usage'], ['Speed to lead', 'Configurable workflow', 'When available', 'Varies'], ['Deployment', 'Guided setup', 'Weeks', 'Days'], ['Languages', 'Hindi, English, Telugu', 'Depends on team', 'Often English-first'], ['Notes', 'Automatic workspace summary', 'Manual', 'Basic']]; return <section id="compare" className="section-ref pt-4"><div className="comparison-head"><span className="eyebrow-ref">A different operating model</span><h2 className="heading-ref mt-2">Your calls should not wait<br />for a shift to begin.</h2></div><div className="comparison-wrap mt-7"><table><thead><tr><th></th><th>Svara</th><th>Telecaller</th><th>Generic AI</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td className={index === 1 ? 'ours' : ''} key={cell}>{cell}</td>)}</tr>)}</tbody></table></div></section>; }

const defaultPlans: Plan[] = [{ id: 'value', name: 'Value', pricePerMin: 3.5, description: 'For focused bulk calling campaigns.', features: ['Native multilingual calling', 'Call summary & fields', 'Campaign controls'] }, { id: 'standard', name: 'Standard', pricePerMin: 5, description: 'For everyday customer conversations.', badge: 'Most popular', features: ['Everything in Value', 'CRM sync', 'WhatsApp actions'] }, { id: 'premium', name: 'Premium', pricePerMin: 7, description: 'For higher-context conversations.', features: ['Everything in Standard', 'Priority routing', 'Custom integrations'] }];
function Pricing() { const [plans, setPlans] = useState<Plan[]>(defaultPlans); useEffect(() => { api<Plan[]>('/api/pricing/plans', undefined, defaultPlans).then((data) => setPlans(data.length ? data : defaultPlans)); }, []); return <section id="pricing" className="pricing-wash"><div className="section-ref py-16"><div className="text-center"><span className="eyebrow-ref">Straightforward usage</span><h2 className="heading-ref mt-2">Pay for active conversations.<br /><span className="text-primary">Keep the rest visible.</span></h2></div><div className="pricing-grid mt-10">{plans.map((plan, index) => <article className={cx('price-card', index === 1 && 'price-featured')} key={plan.id}>{(plan.badge || index === 1) && <span className="popular">{plan.badge || 'Most popular'}</span>}<h3>{plan.name}</h3><p className="price"><b>₹{plan.pricePerMin}</b><small>/ live min</small></p><p className="text-[10px] leading-4 opacity-70">{plan.description || 'A transparent calling plan for your workflow.'}</p><ul>{plan.features.map((feature) => <li key={feature}>✓ {feature}</li>)}</ul><Link href="/signup" className={cx('action w-full', index === 1 ? 'action-light' : 'action-secondary')}>Start calling</Link></article>)}</div><div className="pricing-notes mt-6"><div><b>1. Credit wallet</b><p>Top up in rupees. Your balance is visible before every campaign.</p></div><div><b>2. Live talk-time</b><p>Represent ringing, retries, and policy details accurately in your billing system.</p></div><div><b>3. Dedicated numbers</b><p>Bring in local caller numbers when a team needs its own identity.</p></div></div></div></section>; }

const faqData = [
  ['Capabilities', 'Can Svara speak Indian languages?', 'Start with Hindi, English and Telugu. Language switching is configured per employee and should reflect your available voice coverage.'], ['Setup', 'How is a call started?', 'A form, webhook, CSV row or manual trigger creates an eligible call in the employee queue.'], ['Setup', 'Can I choose the exact script?', 'Yes. Define opening lines, qualifying questions, handoff rules and compliance boundaries.'], ['Billing', 'What does the billed minute include?', 'Show the actual policy in your backend billing system. The UI is designed to make usage information easy to inspect.'], ['Capabilities', 'Can the employee take actions during a call?', 'Configured actions can prepare an approved WhatsApp message, calendar hold, or CRM update for your connected systems.'], ['Reliability', 'What happens when a call cannot connect?', 'The workflow records the result and can surface a scheduled retry rather than silently dropping the lead.'], ['Privacy', 'Where do call notes appear?', 'Summaries and captured fields can be sent to your dashboard and connected destination after the call.'], ['Pricing', 'Can I change plans?', 'Plan availability and changes should be driven by your billing API. The pricing cards are already bound to that endpoint.'],
];
function Faq() { const [open, setOpen] = useState(0); const [query, setQuery] = useState(''); const [category, setCategory] = useState('All'); const categories = ['All', ...Array.from(new Set(faqData.map(([item]) => item)))]; const matches = faqData.filter(([item, question, answer]) => (category === 'All' || item === category) && `${question} ${answer}`.toLowerCase().includes(query.toLowerCase())); return <section id="faq" className="section-ref"><div className="grid gap-9 md:grid-cols-[.34fr_1fr]"><div><span className="eyebrow-ref">Good questions</span><h2 className="heading-ref mt-2">Clear answers to<br />hard questions.</h2><label className="faq-search"><span className="sr-only">Search questions</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search questions" /></label><div className="faq-cats mt-4">{categories.map((item) => <button type="button" key={item} className={category === item ? 'selected' : ''} onClick={() => setCategory(item)}>{item}</button>)}</div></div><div className="faq-list">{matches.length ? matches.map(([, question, answer]) => { const index = faqData.findIndex((item) => item[1] === question); return <button onClick={() => setOpen(open === index ? -1 : index)} aria-expanded={open === index} key={question}><span>{question}</span><b>{open === index ? '−' : '+'}</b>{open === index && <p>{answer}</p>}</button>; }) : <p className="py-5 text-sm text-ink/50">No questions match that search.</p>}</div></div></section>; }

function FinalCta() { return <><section className="cta-wash"><div className="closing-card"><span className="eyebrow-ref">Your first call is closer than you think</span><h2>Give every customer<br />a useful first response.</h2><p>Start a workspace, shape the first workflow, and see the result in a clear team view.</p><div className="mt-6 flex flex-wrap justify-center gap-2"><Link href="/signup" className="action action-primary">Create a workspace →</Link><a href="#top" className="action action-secondary">Try a sample call</a></div></div></section><Footer /></>; }

export function Landing() { return <><Hero /><ProofBar /><LaunchPanel /><HowSteps /><WorkModes /><Capabilities /><IndustryBand /><EmployeeStory /><DataAndDashboard /><CompareTable /><Pricing /><Faq /><FinalCta /><a className="mobile-call-cta" href="#top">☎ Try a call</a></>; }
